### PR TITLE
Internal improvements

### PR DESCRIPTION
**Pull request by kompotkot**
Added spire and brood default urls.

### CODE REVIEW

**Comment by kompotkot** [comment]
@bugout-dev check
- [x] First modify calls for `bugout_api` at brood and spire

**Review by zomglings — APPROVED** [review]
lgtm

**Comment by zomglings** [comment]
To be merged after @kompotkot updates lint.yml to use setup.py

**Comment by kompotkot** [comment]
@bugout-dev summarize

**Pull request merged**
